from django.db import models


class Member(models.Model):
    amana = models.CharField(max_length=40, null=True)
    partyde = models.CharField(max_length=40, null=True)
    amanaQism = models.CharField(max_length=40, null=True)
    amanaSheyakha = models.CharField(max_length=40, null=True)
    amanaCairo = models.CharField(max_length=40, null=True)
    amanaKetaa = models.CharField(max_length=40, null=True)
    Taam = models.CharField(max_length=40, null=True)
    specificLagna = models.CharField(max_length=40, null=True)
    pastParty = models.CharField(max_length=40, null=True)
    manasebAamma = models.CharField(max_length=40, null=True)
    sanaDawra = models.CharField(max_length=40, null=True)
    odwyaSabka = models.CharField(max_length=40, null=True)
    userImg = models.ImageField(upload_to='', null=True, blank=True)
    presidentPartyName = models.CharField(max_length=40, null=True)
    noaaelAdwiaa = models.CharField(max_length=40, null=True)
    famousName = models.CharField(max_length=40, null=True, default=None)
    NationalId = models.CharField(max_length=40, null=True)
    age = models.CharField(max_length=40, null=True)
    yearBirth = models.CharField(max_length=40, null=True)
    monthBirth = models.CharField(max_length=40, null=True)
    dayBirth = models.CharField(max_length=40, null=True)
    education = models.CharField(max_length=40, null=True)
    workProfession = models.CharField(max_length=40, null=True)
    nekaba = models.CharField(max_length=40, null=True)
    ketaaAamel = models.CharField(max_length=40, null=True)
    currentlyWorkProfession = models.CharField(max_length=40, null=True)
    martialStatus = models.CharField(max_length=40, null=True)
    mobileOne = models.CharField(max_length=40, null=True)
    mobileTwo = models.CharField(max_length=40, null=True)
    landline = models.CharField(max_length=40, null=True)
    email = models.CharField(max_length=40, null=True)
    rakmElmabna = models.CharField(max_length=40, null=True)
    street = models.CharField(max_length=40, null=True)
    district = models.CharField(max_length=40, null=True)
    city = models.CharField(max_length=40, null=True)
    # state = models.CharField(max_length=40, null=True)
    qism = models.CharField(max_length=40, null=True)
    ketaa = models.CharField(max_length=40, null=True)
    mohafza = models.CharField(max_length=40, null=True)

    def __str__(self):
        return self.amana