# Generated by Django 4.2.5 on 2024-01-06 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0002_member_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_approved',
            new_name='Approve',
        ),
    ]
