# Generated by Django 4.2.5 on 2024-01-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0004_remove_member_approve_remove_member_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='امانه',
            field=models.CharField(choices=[('عام', 'امانه'), ('امين', 'الصفه الحزبيه')], max_length=40, null=True),
        ),
    ]
