# Generated by Django 4.2.5 on 2024-01-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0005_member_امانه'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='امانه',
            new_name='amr',
        ),
    ]
