# Generated by Django 4.2.5 on 2024-01-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0006_rename_امانه_member_amr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='amr',
        ),
        migrations.AddField(
            model_name='member',
            name='amana',
            field=models.CharField(choices=[('التنظيم', 'التنظيم'), ('عام', 'عام')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='detail_party',
            field=models.CharField(choices=[('امين', 'امين'), ('مساعد امين', 'مساعد امين')], max_length=40, null=True),
        ),
    ]
