# Generated by Django 4.2.5 on 2024-01-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0007_remove_member_amr_member_amana_member_detail_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amana_qetaa',
            field=models.CharField(choices=[('شمال', 'شمال'), ('جنوب', 'جنوب')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='amana_qism',
            field=models.CharField(choices=[('شبرا', 'شبرا'), ('الزيتون', 'الزيتون')], max_length=40, null=True),
        ),
    ]
