# Generated by Django 4.2.5 on 2024-01-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0008_member_amana_qetaa_member_amana_qism'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='country',
            new_name='sheyakha',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='tam',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.AddField(
            model_name='member',
            name='amana_cairo',
            field=models.CharField(choices=[('القاهرة', 'القاهرة')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='specfic_lagna',
            field=models.CharField(choices=[('لجنة الطاقة', 'لجنة الطاقة'), ('لجنة الصحة', 'لجنة الصحة')], max_length=255, null=True),
        ),
    ]
