# Generated by Django 4.2.5 on 2024-01-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0009_rename_country_member_sheyakha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sheyakha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='tam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
