# Generated by Django 4.2.5 on 2024-01-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0010_alter_member_sheyakha_alter_member_tam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='amana_cairo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='amana_qetaa',
        ),
        migrations.RemoveField(
            model_name='member',
            name='amana_qism',
        ),
        migrations.RemoveField(
            model_name='member',
            name='detail_party',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sheyakha',
        ),
        migrations.RemoveField(
            model_name='member',
            name='specfic_lagna',
        ),
        migrations.RemoveField(
            model_name='member',
            name='tam',
        ),
    ]
