# Generated by Django 4.2.5 on 2024-01-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0011_remove_member_amana_cairo_remove_member_amana_qetaa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amana_cairo',
            field=models.CharField(choices=[('القاهرة', 'القاهرة')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='amana_qetaa',
            field=models.CharField(choices=[('شمال', 'شمال'), ('جنوب', 'جنوب')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='amana_qism',
            field=models.CharField(choices=[('شبرا', 'شبرا'), ('الزيتون', 'الزيتون')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='detail_party',
            field=models.CharField(choices=[('امين', 'امين'), ('مساعد امين', 'مساعد امين')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sheyakha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='specfic_lagna',
            field=models.CharField(choices=[('لجنة الطاقة', 'لجنة الطاقة'), ('لجنة الصحة', 'لجنة الصحة')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='tam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
