# Generated by Django 4.2.5 on 2024-01-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0012_member_amana_cairo_member_amana_qetaa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='detail_party',
            new_name='detail',
        ),
        migrations.RemoveField(
            model_name='member',
            name='amana_cairo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='amana_qetaa',
        ),
        migrations.RemoveField(
            model_name='member',
            name='amana_qism',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sheyakha',
        ),
        migrations.RemoveField(
            model_name='member',
            name='specfic_lagna',
        ),
        migrations.RemoveField(
            model_name='member',
            name='tam',
        ),
    ]
