# Generated by Django 4.2.5 on 2024-01-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0013_rename_detail_party_member_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='detail',
            new_name='partyde',
        ),
    ]
