# Generated by Django 4.2.5 on 2024-01-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0015_remove_member_amana'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amana',
            field=models.CharField(choices=[('التنظيم', 'التنظيم'), ('عام', 'عام')], max_length=40, null=True),
        ),
    ]
