# Generated by Django 4.2.5 on 2024-01-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0016_member_amana'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amana_qism',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='amana',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='partyde',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
