# Generated by Django 4.2.5 on 2024-01-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0017_member_amana_qism_alter_member_amana_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='amana_qism',
            new_name='amanaQ',
        ),
    ]
