# Generated by Django 4.2.5 on 2024-01-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0019_rename_amanaq_member_nationalid_member_taam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='state',
        ),
    ]
