# Generated by Django 4.2.5 on 2024-01-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0020_remove_member_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='NationalId',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Taam',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='amana',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='amanaCairo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='amanaKetaa',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='amanaQism',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='amanaSheyakha',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='currentlyWorkProfession',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='dayBirth',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='district',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='education',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='famousName',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ketaa',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ketaaAamel',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='landline',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='manasebAamma',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='martialStatus',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobileOne',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobileTwo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mohafza',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='monthBirth',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='nekaba',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='noaaelAdwiaa',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='odwyaSabka',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='partyde',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='pastParty',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='presidentPartyName',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='qism',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='rakmElmabna',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='sanaDawra',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='specificLagna',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='street',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='workProfession',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='yearBirth',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
