# Generated by Django 4.2.5 on 2024-01-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0022_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
