# Generated by Django 4.2.5 on 2024-02-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addUser', '0024_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='NationalIdImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
