# Generated by Django 4.2.5 on 2024-01-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=222)),
                ('lName', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=222)),
                ('lName', models.CharField(max_length=222)),
                ('age', models.IntegerField()),
                ('classroom', models.IntegerField()),
            ],
        ),
    ]
