# Generated by Django 4.2.5 on 2024-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_author_post_delete_admin_delete_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(to='guest.author'),
        ),
    ]
